import type { IncomeSource } from "./types";

const SOURCE_KEYWORDS: [RegExp, IncomeSource][] = [
  [/сайт/i, "SITE"],
  [/инстаграм|instagram/i, "INSTAGRAM"],
  [/реклам/i, "ADS"],
  [/сарафан/i, "WORD_OF_MOUTH"],
];

function guessSource(title: string): IncomeSource | undefined {
  for (const [re, code] of SOURCE_KEYWORDS) {
    if (re.test(title)) return code;
  }
  return undefined;
}

// Some cards have a structured desc (Name:/Address:/... — looks auto-generated by a
// lead form), others are just free text a person typed. Only pull buyer/city out of
// the structured kind — free text is too unreliable to parse and gets left for the
// person to fill in from what they can see on the card themselves.
function parseStructuredDesc(desc: string): { buyer?: string; city?: string } {
  const nameMatch = desc.match(/^Name:\s*(.+)$/im);
  const addressMatch = desc.match(/^Address:\s*(.+)$/im);
  return {
    buyer: nameMatch?.[1]?.trim() || undefined,
    city: addressMatch?.[1]?.trim() || undefined,
  };
}

export function incomeDefaultsFromCard(card: { name: string; desc: string }) {
  const { buyer, city } = parseStructuredDesc(card.desc);
  return {
    saleDetails: card.name,
    source: guessSource(card.name),
    buyer,
    city,
  };
}
